---
- name: restart ssh
  service: name=sshd state=restarted
  become: yes

- name: restart ntpd
  service: name=ntpd state=restarted
  become: yes

- name: new aliases
  command: /usr/bin/newaliases
  become: yes


