---
- name: install required packages
  become: yes
  openbsd_pkg:
    state: present
    name:
      - curl
      - wget
      - git
      - python--%3.6
      - py3-pip
      - py3-setuptools

- name: install pip virtualenv
  pip:
    name: virtualenv

- name: Copy GIT Repo
  git:
    repo: 'https://{{gituser}}:{{gitpass}}@gitea.tostr.io/cyn/CryptoPi.git'
    dest: /home/cyn/code

- name: install pip packages
  pip:
    requirements: requirements.txt
    virtualenv: /home/cyn/code/CryptoPi/venv

