---
- name: install required packages
  become: yes
  openbsd_pkg:
    state: present
    name:
      - curl
      - wget
      - git
      - python--%3.6
      - py3-pip
      - py3-setuptools

- name: install pip virtualenv
  pip:
    name: virtualenv
    executable: pip3

- name: Copy GIT Repo
  become: yes
  become_user: cyn
  git:
    repo: 'https://{{gituser}}:{{gitpass}}@gitea.tostr.io/cyn/CynFlask.git'
    dest: /home/cyn/code/CynFlask

#- name: create virtual environment
#  become: yes
#  become_user: cyn
#  command: python3 -m venv /home/cyn/code/CryptoPi/venv

- name: install pip packages
  pip:
    requirements: /home/cyn/code/CynFlask/etc/requirements.txt
    virtualenv: /home/cyn/code/CynFlask/.venv
    virtualenv_command: /usr/local/bin/python3 -m venv
    #virtualenv_python: python3.6

- name: fix python venv permissions
  file: 
    dest: /home/cyn/code/CynFlask/.venv
    owner: cyn
    group: cyn
    recurse: yes
