# vim: set ft=yaml.ansible:
---
- hosts: all
  user: deploy
  become_method: doas
  roles:
    - init

- hosts: greed
  user: deploy
  become_method: doas
  roles: 
    - init
    - web

- hosts: aws
  user: deploy
  become_method: doas
  roles:
    - mailserver

